name: retrixe-control-center
version: '1.0.0-dev.git'
license: GPL-3.0+
title: Control Panel
summary: A Linux app for settings usually not in your desktop's Settings app.
description: |
  A Linux app for settings usually not in your desktop's Settings app.
  Currently only supports changing Lenovo laptops' Conservation Mode
  and reclocking GPUs using the nouveau driver (experimental).

base: core18
grade: devel
confinement: devmode
compression: lzo

# https://snapcraft.io/docs/interface-management
# https://snapcraft.io/docs/desktop-menu-icon-support
parts:
  control-center:
    plugin: flutter
    source: ./app
    flutter-target: lib/main.dart
  control-center-daemon:
    plugin: go
    source: ./daemon
    source-type: local
    build-packages:
      - gcc
      - libgl1-mesa-dev
      - xorg-dev

apps:
  retrixe-control-center:
    command: controlcenter
    extensions: [flutter-stable]
    slots:
      - dbus-daemon
  daemon: # retrixe-control-center.daemon
    command: daemon --daemon
    daemon: simple
    slots:
      - sysfs-access
      - dbus-daemon

slots:
  sysfs-access:
    interface: system-files
    read: [/sys]
    write: [/sys]
  dbus-daemon:
    interface: dbus
    bus: system
    name: com.retrixe.ControlCenter.v0
