name: control-center
version: 'git'
license: GPL-3.0+
title: Control Panel
summary: A Linux app for settings usually not in your desktop's Settings app.
description: |
  A Linux app for settings usually not in your desktop's Settings app.
  Currently supports Lenovo laptops' Conservation Mode
  and experimental reclocking for nouveau-powered GPUs.

base: core18
grade: devel
compression: lzo
confinement: strict

# https://docs.flutter.dev/deployment/linux
# https://snapcraft.io/docs/interface-management
parts:
  control-center:
    plugin: flutter
    source: ./app
    source-type: local
    flutter-target: lib/main.dart
  control-center-daemon:
    plugin: go
    source: ./daemon
    source-type: local
    build-packages:
      - gcc

apps:
  control-center:
    command: control_center
    extensions: [flutter-stable]
    plugs:
      - dbus-daemon-access
  daemon: # control-center.daemon
    command: daemon
    daemon: simple
    plugs:
      - sysfs-access
    slots:
      - dbus-daemon

plugs:
  sysfs-access:
    interface: system-files
    read: [/sys]
    write: [/sys]
  dbus-daemon-access:
    interface: dbus
    bus: system
    name: com.retrixe.ControlCenter.v0

slots:
  dbus-daemon:
    interface: dbus
    bus: system
    name: com.retrixe.ControlCenter.v0
